#ifndef __entropic_config_h_
#define __entropic_config_h_
/*     ###########    W A R N I N G ! ! !    ##########     */
/*     ##  Do not edit this file! it is generated!   ##     */
/*     ###########    W A R N I N G ! ! !    ##########     */
#define ECFG_CHIP_ZIP1    0
#define ECFG_CHIP_ZIP2    0
#define ECFG_CHIP_MAVERICKS    0
#define ECFG_CHIP_SWAMIS    0
#define ECFG_CHIP_JAWS    0
#define ECFG_CHIP_BALBOA    1
#define ECFG_CHIP_STRING     "ECFG_CHIP_BALBOA"

#define ECFG_BOARD_ECB_PCI_ZIP2    0
#define ECFG_BOARD_PC_PCI_ZIP2    0
#define ECFG_BOARD_PC_PCI_ZIP1    0
#define ECFG_BOARD_PC_DVT_MII_ZIP2    0
#define ECFG_BOARD_PC_DVT_TMII_ZIP2    0
#define ECFG_BOARD_PC_DVT_GMII_ZIP2    0
#define ECFG_BOARD_PC_DVT2_PCI_ZIP2    0
#define ECFG_BOARD_PC_PCIE_MAVERICKS    0
#define ECFG_BOARD_PC_XMII_BALBOA    1
#define ECFG_BOARD_COLDFIRE_DVT_FLEX_ZIP2    0
#define ECFG_BOARD_ECB_ROW    0
#define ECFG_BOARD_GPC    0
#define ECFG_BOARD_ECB_3M_L3    0
#define ECFG_BOARD_ECB_5M_L3    0
#define ECFG_BOARD_ECB_6M_L3    0
#define ECFG_BOARD_ECB_PCIE_MAVERICKS    0
#define ECFG_BOARD_HOSTLESS    0
#define ECFG_BOARD_STRING     "ECFG_BOARD_PC_XMII_BALBOA"

#define ECFG_NETWORK_ACCESS    0
#define ECFG_NETWORK_MIDRF_MESH    0
#define ECFG_NETWORK_HIRF_MESH    1
#define ECFG_NETWORK_STRING     "ECFG_NETWORK_HIRF_MESH"

#define ECFG_NODE_CPE    0
#define ECFG_NODE_HEADEND    0
#define ECFG_NODE_TCPE    0
#define ECFG_NODE_MOCA    1
#define ECFG_NODE_STRING     "ECFG_NODE_MOCA"

#define ECFG_OS_LINUX_TYPICAL    0
#define ECFG_OS_NONE    1
#define ECFG_OS_STRING     "ECFG_OS_NONE"

#define ECFG_FLAVOR_PRODUCTION    1
#define ECFG_FLAVOR_PRODUCTION_PROTEM    0
#define ECFG_FLAVOR_PHYSVT    0
#define ECFG_FLAVOR_VALIDATION    0
#define ECFG_FLAVOR_STRING     "ECFG_FLAVOR_PRODUCTION"

#define ECFG_DATAPATH_GMII    1
#define ECFG_DATAPATH_RGMII    0
#define ECFG_DATAPATH_TMII    0
#define ECFG_DATAPATH_MII    0
#define ECFG_DATAPATH_PCI    0
#define ECFG_DATAPATH_PCIE    0
#define ECFG_DATAPATH_FLEX    0
#define ECFG_DATAPATH_STRING     "ECFG_DATAPATH_GMII"

#define ECFG_MISC_REF_XTAL_25M_CLOCK    1
#define ECFG_MISC_REF_SOC_25M_CLOCK    0
#define ECFG_MISC_STRING     "ECFG_MISC_REF_XTAL_25M_CLOCK"


#endif

