###############################################################################
#
# File: Makefile
#
# Copyright 2012 TiVo Inc.  All Rights Reserved.
#
###############################################################################

ISM_DEPTH := .
include $(ISM_DEPTH)/ismdefs

DIRS := \
	$(DIRECTFB_RELEASE) \
	$(NULL)

include $(ISMRULES)

