###############################################################################
#
# Copyright 2013 TiVo Inc. All Rights Reserved.
#
###############################################################################

ISM_DEPTH := ..
include $(ISM_DEPTH)/ismdefs

NMTARGETS_SO += \
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/gthread/.libs/libgthread-2.0.nm \
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/gobject/.libs/libgobject-2.0.nm \
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/glib/.libs/libglib-2.0.nm \
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/gmodule/.libs/libgmodule-2.0.nm \
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/gio/.libs/libgio-2.0.nm \
	$(NULL)

include $(ISMRULES)
