#
# File: Makefile
#
# Copyright (c) 2009 TiVo Inc.
#
###############################################################################


ISM_DEPTH=.
include $(ISM_DEPTH)/ismdefs

ifeq ($(BOOTARCH),mips)
DIRS=ffmpeg-0.5
else
default:
endif

include $(COMMONRULES)
