#
# File: Makefile (mount top-level Makefile for Linux)
#
# Copyright (C) 1998-1999 TiVo, Inc.  All rights reserved.
#
###############################################################################

ISM_DEPTH	:= ./..
include $(ISM_DEPTH)/ismdefs

DIRS := lib mount

include $(ISMRULES)

