/* Generated by ffconf */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#include <endian.h>
#ifdef __BIG_ENDIAN__
#define AV_HAVE_BIGENDIAN 1
#elif __BYTE_ORDER == __BIG_ENDIAN
#define AV_HAVE_BIGENDIAN 1
#else
#define AV_HAVE_BIGENDIAN 0
#endif //__BIG_ENDIAN__
#define AV_HAVE_FAST_UNALIGNED 0
#endif /* AVUTIL_AVCONFIG_H */
