#
# File: Makefile
#
# Copyright (c) 2009 TiVo Inc.
#
###############################################################################

ISM_DEPTH       := .
include $(ISM_DEPTH)/ismdefs

DIRS := rp-l2tp-0.4-tivo

include $(ISMRULES)

