#
# File: Makefile
#
# Copyright (c) 2013 TiVo Inc.
#
###############################################################################


ISM_DEPTH=.
include $(ISM_DEPTH)/ismdefs

DIRS=libnl-3.2.18

include $(COMMONRULES)
