###############################################################################
#
# Copyright 2013 TiVo Inc. All Rights Reserved.
#
###############################################################################

ISM_DEPTH := ..
include $(ISM_DEPTH)/ismdefs

NMTARGETS_SO +=											\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/gst/.libs/libgstreamer-0.10.nm				\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/libs/gst/base/.libs/libgstbase-0.10.nm			\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/libs/gst/check/.libs/libgstcheck-0.10.nm		\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/libs/gst/controller/.libs/libgstcontroller-0.10.nm	\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/libs/gst/dataprotocol/.libs/libgstdataprotocol-0.10.nm	\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/libs/gst/net/.libs/libgstnet-0.10.nm			\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/plugins/elements/.libs/libgstcoreelements.nm		\
	$(ISM_DEPTH)/$(TIVO_SYSTEM)/plugins/indexers/.libs/libgstcoreindexers.nm		\
	$(NULL)

include $(ISMRULES)
