#
# File: Makefile
#
# Copyright 2009 TiVo Inc. All Rights Reserved.
#
###############################################################################

ISM_DEPTH       = ./..
include $(ISM_DEPTH)/ismdefs

IPTABLES_RELEASE = iptables-1.4.3.2

DIRS := $(IPTABLES_RELEASE)

include $(ISMRULES)

