#
# File: Makefile
#
# Copyright 2012 TiVo Inc. All Rights Reserved.
#
#############################################################

ISM_DEPTH=.
include $(ISM_DEPTH)/ismdefs

DIRS=ffmpeg-0.10.3

include $(COMMONRULES)
